queue:
  name: Hosted Linux Preview
steps:
- task: Docker@0
  inputs:
    containerregistrytype: "Container Registry"
    dockerRegistryEndpoint: "Docker Hub"
    action: "Build an image"
    imageName: "$(Build.Repository.Name):$(Build.BuildNumber)"
    qualifyImageName: "false"
    includeLatestTag: "true"
    workingDirectory: Deck2MTGA.Web

- task: Docker@0
  inputs:
    containerregistrytype: "Container Registry"
    dockerRegistryEndpoint: "Docker Hub"
    action: "Push an image"
    imageName: "$(Build.Repository.Name):$(Build.BuildNumber)"
    qualifyImageName: "false"
    includeLatestTag: "true"

